//
//  Poems.swift
//  
//
//  Created by Jimmy Hoang on 2017-07-17.
//
//

import Foundation

class Poems {
    var jsonData: [String] = [
    "From fairest creatures we desire increase, that thereby beauty's rose might never die, but as the riper should by time decease, his tender heir might bear his memory: But thou contracted to thine own bright eyes, Feed'st thy light's flame with self-substantial fuel, Making a famine where abundance lies.",
    "When forty winters shall besiege thy brow, And dig deep trenches in thy beauty's field, Thy youth's proud livery so gazed on now, Will be a tatter'd weed of small worth held:Then being asked, where all thy beauty lies, Where all the treasure of thy lusty days; To say, within thine own deep sunken eyes, Were an all-eating shame, and thriftless praise.",
    "Look in thy glass and tell the face thou viewest Now is the time that face should form another; Whose fresh repair if now thou not renewest, Thou dost beguile the world, unbless some mother. For where is she so fair whose unear'd womb Disdains the tillage of thy husbandry? Or who is he so fond will be the tomb, Of his self-love to stop posterity?",
    "Unthrifty loveliness, why dost thou spend Upon thy self thy beauty's legacy? Nature's bequest gives nothing, but doth lend, And being frank she lends to those are free: Then, beauteous niggard, why dost thou abuse The bounteous largess given thee to give? Profitless usurer, why dost thou use So great a sum of sums, yet canst not live?",
    "Those hours, that with gentle work did frame The lovely gaze where every eye doth dwell, Will play the tyrants to the very same And that unfair which fairly doth excel; For never-resting time leads summer on To hideous winter, and confounds him there; Sap checked with frost, and lusty leaves quite gone, Beauty o'er-snowed and bareness everywhere.",
    "Then let not winter's ragged hand deface, In thee thy summer, ere thou be distill'd: Make sweet some vial; treasure thou some place With beauty's treasure ere it be self-kill'd. That use is not forbidden usury, Which happies those that pay the willing loan; That's for thy self to breed another thee.",
    "Lo! in the orient when the gracious light Lifts up his burning head, each under eye Doth homage to his new-appearing sight, Serving with looks his sacred majesty; And having climb'd the steep-up heavenly hill, Resembling strong youth in his middle age, Yet mortal looks adore his beauty still, Attending on his golden pilgrimage.",
    "Music to hear, why hear'st thou music sadly? Sweets with sweets war not, joy delights in joy: Why lov'st thou that which thou receiv'st not gladly, Or else receiv'st with pleasure thine annoy? If the true concord of well-tuned sounds, By unions married, do offend thine ear, They do but sweetly chide thee.",
    "Is it for fear to wet a widow's eye, That thou consum'st thy self in single life? Ah! if thou issueless shalt hap to die, The world will wail thee like a makeless wife;The world will be thy widow and still weep That thou no form of thee hast left behind, When every private widow well may keep By children's eyes, her husband's shape in mind: Look!",
    "For shame! deny that thou bear'st love to any, Who for thy self art so unprovident. Grant, if thou wilt, thou art belov'd of many, But that thou none lov'st is most evident: For thou art so possess'd with murderous hate, That 'gainst thy self thou stick'st not to conspire, Seeking that beauteous roof to ruinate Which to repair should be thy chief desire.",
    "As fast as thou shalt wane, so fast thou grow'st, In one of thine, from that which thou departest; And that fresh blood which youngly thou bestow'st, Thou mayst call thine when thou from youth convertest, Herein lives wisdom, beauty, and increase; Without this folly, age, and cold decay.",
    "When I do count the clock that tells the time, And see the brave day sunk in hideous night; When I behold the violet past prime And sable curls, all silvered o'er with white; When lofty trees I barren of leaves, Which erst from heat did canopy the herd, And summer's green all girded up in sheaves, Borne on the bier with white and bristly beard.",
    "O! that you were your self; but, love you are No longer yours, than you your self here live: Against this coming end you should prepare, And your sweet semblance to some other give: So should that beauty which you hold in lease Find no determination; then you were Yourself again, after yourself's decease, When your sweet issue your sweet form should bear.",
    "Not from the stars do I my judgement pluck; And yet methinks I have astronomy, But not to tell of good or evil luck, Of plagues, of dearths, or seasons' quality; Nor can I fortune to brief minutes tell, Pointing to each his thunder, rain and wind.",
    "How can I then return in happy plight, That am debarre'd the benefit of rest? When day's oppression is not eas'd by night, But day by night and night by day oppress'd, And each, though enemies to either's reign, Do in consent shake hands to torture me, The one by toil, the other to complain How far I toil, still farther off from thee.",
    "When in disgrace with fortune and men's eyes I all alone beweep my outcast state, And trouble deaf heaven with my bootless cries, And look upon myself, and curse my fate, Wishing me like to one more rich in hope, Featur'd like him, like him with friends possess'd, Desiring this man's art, and that man's scope, With what I most enjoy contented least",
    "When to the sessions of sweet silent thought I summon up remembrance of things past, I sigh the lack of many a thing I sought, And with old woes new wail my dear time's waste: Then can I drown an eye, unused to flow, For precious friends hid in death's dateless night, And weep afresh love's long since cancell'd woe, And moan the expense of many a vanish'd sight.",
    "How careful was I when I took my way, Each trifle under truest bars to thrust, That to my use it might unused stay From hands of falsehood, in sure wards of trust! But thou, to whom my jewels trifles are, Most worthy comfort, now my greatest grief, Thou best of dearest, and mine only care, Art left the prey of every vulgar thief.",
    "That time of year thou mayst in me behold When yellow leaves, or none, or few, do hang Upon those boughs which shake against the cold, Bare ruin'd choirs, where late the sweet birds sang. In me thou see'st the twilight of such day As after sunset fadeth in the west; Which by and by black night doth take away, Death's second self, that seals up all in rest.",
    "Say that thou didst forsake me for some fault, And I will comment upon that offence: Speak of my lameness, and I straight will halt, Against thy reasons making no defence.",
    "Euripides, and Sophocles to us, Pacuvius, Accius, him of Cordova dead, To live again, to hear thy buskin tread, And shake a stage; or, when thy socks were on, Leave thee alone for the comparison Of all that insolent Greece or haughty Rome Sent forth, or since did from their ashes come."
    ]
}
